// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/ac.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_INCREMENT Operation = 0
	Operation_DECREMENT Operation = 1
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "INCREMENT",
		1: "DECREMENT",
	}
	Operation_value = map[string]int32{
		"INCREMENT": 0,
		"DECREMENT": 1,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ac_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_proto_ac_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_ac_proto_rawDescGZIP(), []int{0}
}

type UpdateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	OriginNodeId  string                 `protobuf:"bytes,2,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Op            Operation              `protobuf:"varint,4,opt,name=op,proto3,enum=ac.Operation" json:"op,omitempty"`
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	UpdateId      string                 `protobuf:"bytes,6,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessage) Reset() {
	*x = UpdateMessage{}
	mi := &file_proto_ac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessage) ProtoMessage() {}

func (x *UpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessage.ProtoReflect.Descriptor instead.
func (*UpdateMessage) Descriptor() ([]byte, []int) {
	return file_proto_ac_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateMessage) GetOriginNodeId() string {
	if x != nil {
		return x.OriginNodeId
	}
	return ""
}

func (x *UpdateMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UpdateMessage) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_INCREMENT
}

func (x *UpdateMessage) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *UpdateMessage) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

type CLConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MaxQueueSize  int32                  `protobuf:"varint,2,opt,name=max_queue_size,json=maxQueueSize,proto3" json:"max_queue_size,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLConfig) Reset() {
	*x = CLConfig{}
	mi := &file_proto_ac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLConfig) ProtoMessage() {}

func (x *CLConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLConfig.ProtoReflect.Descriptor instead.
func (*CLConfig) Descriptor() ([]byte, []int) {
	return file_proto_ac_proto_rawDescGZIP(), []int{1}
}

func (x *CLConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CLConfig) GetMaxQueueSize() int32 {
	if x != nil {
		return x.MaxQueueSize
	}
	return 0
}

func (x *CLConfig) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_ac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_ac_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	UpdateId      string                 `protobuf:"bytes,2,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAck) Reset() {
	*x = UpdateAck{}
	mi := &file_proto_ac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAck) ProtoMessage() {}

func (x *UpdateAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAck.ProtoReflect.Descriptor instead.
func (*UpdateAck) Descriptor() ([]byte, []int) {
	return file_proto_ac_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAck) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateAck) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

func (x *UpdateAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_ac_proto protoreflect.FileDescriptor

const file_proto_ac_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ac.proto\x12\x02ac\"\xb7\x01\n" +
	"\rUpdateMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x0eorigin_node_id\x18\x02 \x01(\tR\foriginNodeId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\x02op\x18\x04 \x01(\x0e2\r.ac.OperationR\x02op\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x12\x1b\n" +
	"\tupdate_id\x18\x06 \x01(\tR\bupdateId\"a\n" +
	"\bCLConfig\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x0emax_queue_size\x18\x02 \x01(\x05R\fmaxQueueSize\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"T\n" +
	"\tUpdateAck\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tupdate_id\x18\x02 \x01(\tR\bupdateId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess*)\n" +
	"\tOperation\x12\r\n" +
	"\tINCREMENT\x10\x00\x12\r\n" +
	"\tDECREMENT\x10\x012u\n" +
	"\tACService\x127\n" +
	"\x0fPropagateUpdate\x12\x11.ac.UpdateMessage\x1a\r.ac.UpdateAck(\x010\x01\x12/\n" +
	"\x16ChangeConsistencyLevel\x12\f.ac.CLConfig\x1a\a.ac.AckB,Z*github.com/weufhsos/adaptive_sync_go/protob\x06proto3"

var (
	file_proto_ac_proto_rawDescOnce sync.Once
	file_proto_ac_proto_rawDescData []byte
)

func file_proto_ac_proto_rawDescGZIP() []byte {
	file_proto_ac_proto_rawDescOnce.Do(func() {
		file_proto_ac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ac_proto_rawDesc), len(file_proto_ac_proto_rawDesc)))
	})
	return file_proto_ac_proto_rawDescData
}

var file_proto_ac_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ac_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ac_proto_goTypes = []any{
	(Operation)(0),        // 0: ac.Operation
	(*UpdateMessage)(nil), // 1: ac.UpdateMessage
	(*CLConfig)(nil),      // 2: ac.CLConfig
	(*Ack)(nil),           // 3: ac.Ack
	(*UpdateAck)(nil),     // 4: ac.UpdateAck
}
var file_proto_ac_proto_depIdxs = []int32{
	0, // 0: ac.UpdateMessage.op:type_name -> ac.Operation
	1, // 1: ac.ACService.PropagateUpdate:input_type -> ac.UpdateMessage
	2, // 2: ac.ACService.ChangeConsistencyLevel:input_type -> ac.CLConfig
	4, // 3: ac.ACService.PropagateUpdate:output_type -> ac.UpdateAck
	3, // 4: ac.ACService.ChangeConsistencyLevel:output_type -> ac.Ack
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ac_proto_init() }
func file_proto_ac_proto_init() {
	if File_proto_ac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ac_proto_rawDesc), len(file_proto_ac_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ac_proto_goTypes,
		DependencyIndexes: file_proto_ac_proto_depIdxs,
		EnumInfos:         file_proto_ac_proto_enumTypes,
		MessageInfos:      file_proto_ac_proto_msgTypes,
	}.Build()
	File_proto_ac_proto = out.File
	file_proto_ac_proto_goTypes = nil
	file_proto_ac_proto_depIdxs = nil
}
