// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/ac.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ACServiceClient is the client API for ACService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ACServiceClient interface {
	// 核心同步接口：接收远程更新
	PropagateUpdate(ctx context.Context, opts ...grpc.CallOption) (ACService_PropagateUpdateClient, error)
	// 接收配置变更（OCA模块下发）
	ChangeConsistencyLevel(ctx context.Context, in *CLConfig, opts ...grpc.CallOption) (*Ack, error)
}

type aCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewACServiceClient(cc grpc.ClientConnInterface) ACServiceClient {
	return &aCServiceClient{cc}
}

func (c *aCServiceClient) PropagateUpdate(ctx context.Context, opts ...grpc.CallOption) (ACService_PropagateUpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &ACService_ServiceDesc.Streams[0], "/ac.ACService/PropagateUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &aCServicePropagateUpdateClient{stream}
	return x, nil
}

type ACService_PropagateUpdateClient interface {
	Send(*UpdateMessage) error
	Recv() (*UpdateAck, error)
	grpc.ClientStream
}

type aCServicePropagateUpdateClient struct {
	grpc.ClientStream
}

func (x *aCServicePropagateUpdateClient) Send(m *UpdateMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aCServicePropagateUpdateClient) Recv() (*UpdateAck, error) {
	m := new(UpdateAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aCServiceClient) ChangeConsistencyLevel(ctx context.Context, in *CLConfig, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/ac.ACService/ChangeConsistencyLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ACServiceServer is the server API for ACService service.
// All implementations must embed UnimplementedACServiceServer
// for forward compatibility
type ACServiceServer interface {
	// 核心同步接口：接收远程更新
	PropagateUpdate(ACService_PropagateUpdateServer) error
	// 接收配置变更（OCA模块下发）
	ChangeConsistencyLevel(context.Context, *CLConfig) (*Ack, error)
	mustEmbedUnimplementedACServiceServer()
}

// UnimplementedACServiceServer must be embedded to have forward compatible implementations.
type UnimplementedACServiceServer struct {
}

func (UnimplementedACServiceServer) PropagateUpdate(ACService_PropagateUpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method PropagateUpdate not implemented")
}
func (UnimplementedACServiceServer) ChangeConsistencyLevel(context.Context, *CLConfig) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeConsistencyLevel not implemented")
}
func (UnimplementedACServiceServer) mustEmbedUnimplementedACServiceServer() {}

// UnsafeACServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ACServiceServer will
// result in compilation errors.
type UnsafeACServiceServer interface {
	mustEmbedUnimplementedACServiceServer()
}

func RegisterACServiceServer(s grpc.ServiceRegistrar, srv ACServiceServer) {
	s.RegisterService(&ACService_ServiceDesc, srv)
}

func _ACService_PropagateUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ACServiceServer).PropagateUpdate(&aCServicePropagateUpdateServer{stream})
}

type ACService_PropagateUpdateServer interface {
	Send(*UpdateAck) error
	Recv() (*UpdateMessage, error)
	grpc.ServerStream
}

type aCServicePropagateUpdateServer struct {
	grpc.ServerStream
}

func (x *aCServicePropagateUpdateServer) Send(m *UpdateAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aCServicePropagateUpdateServer) Recv() (*UpdateMessage, error) {
	m := new(UpdateMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ACService_ChangeConsistencyLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CLConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACServiceServer).ChangeConsistencyLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ac.ACService/ChangeConsistencyLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACServiceServer).ChangeConsistencyLevel(ctx, req.(*CLConfig))
	}
	return interceptor(ctx, in, info, handler)
}

// ACService_ServiceDesc is the grpc.ServiceDesc for ACService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ACService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ac.ACService",
	HandlerType: (*ACServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeConsistencyLevel",
			Handler:    _ACService_ChangeConsistencyLevel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PropagateUpdate",
			Handler:       _ACService_PropagateUpdate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ac.proto",
}