// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: proto/ac.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ACService_PropagateUpdate_FullMethodName        = "/ac.ACService/PropagateUpdate"
	ACService_ChangeConsistencyLevel_FullMethodName = "/ac.ACService/ChangeConsistencyLevel"
)

// ACServiceClient is the client API for ACService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ACServiceClient interface {
	PropagateUpdate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpdateMessage, UpdateAck], error)
	ChangeConsistencyLevel(ctx context.Context, in *CLConfig, opts ...grpc.CallOption) (*Ack, error)
}

type aCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewACServiceClient(cc grpc.ClientConnInterface) ACServiceClient {
	return &aCServiceClient{cc}
}

func (c *aCServiceClient) PropagateUpdate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpdateMessage, UpdateAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ACService_ServiceDesc.Streams[0], ACService_PropagateUpdate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateMessage, UpdateAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ACService_PropagateUpdateClient = grpc.BidiStreamingClient[UpdateMessage, UpdateAck]

func (c *aCServiceClient) ChangeConsistencyLevel(ctx context.Context, in *CLConfig, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ACService_ChangeConsistencyLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ACServiceServer is the server API for ACService service.
// All implementations must embed UnimplementedACServiceServer
// for forward compatibility.
type ACServiceServer interface {
	PropagateUpdate(grpc.BidiStreamingServer[UpdateMessage, UpdateAck]) error
	ChangeConsistencyLevel(context.Context, *CLConfig) (*Ack, error)
	mustEmbedUnimplementedACServiceServer()
}

// UnimplementedACServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedACServiceServer struct{}

func (UnimplementedACServiceServer) PropagateUpdate(grpc.BidiStreamingServer[UpdateMessage, UpdateAck]) error {
	return status.Error(codes.Unimplemented, "method PropagateUpdate not implemented")
}
func (UnimplementedACServiceServer) ChangeConsistencyLevel(context.Context, *CLConfig) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeConsistencyLevel not implemented")
}
func (UnimplementedACServiceServer) mustEmbedUnimplementedACServiceServer() {}
func (UnimplementedACServiceServer) testEmbeddedByValue()                   {}

// UnsafeACServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ACServiceServer will
// result in compilation errors.
type UnsafeACServiceServer interface {
	mustEmbedUnimplementedACServiceServer()
}

func RegisterACServiceServer(s grpc.ServiceRegistrar, srv ACServiceServer) {
	// If the following call panics, it indicates UnimplementedACServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ACService_ServiceDesc, srv)
}

func _ACService_PropagateUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ACServiceServer).PropagateUpdate(&grpc.GenericServerStream[UpdateMessage, UpdateAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ACService_PropagateUpdateServer = grpc.BidiStreamingServer[UpdateMessage, UpdateAck]

func _ACService_ChangeConsistencyLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CLConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACServiceServer).ChangeConsistencyLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACService_ChangeConsistencyLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACServiceServer).ChangeConsistencyLevel(ctx, req.(*CLConfig))
	}
	return interceptor(ctx, in, info, handler)
}

// ACService_ServiceDesc is the grpc.ServiceDesc for ACService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ACService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ac.ACService",
	HandlerType: (*ACServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeConsistencyLevel",
			Handler:    _ACService_ChangeConsistencyLevel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PropagateUpdate",
			Handler:       _ACService_PropagateUpdate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ac.proto",
}
